# -*- coding: utf-8 -*-
"""Domain configuration for avian expert system."""

from __future__ import annotations

from dataclasses import dataclass


# Recognition modes for inference
RECOGNITION_MODE_FORWARD = "adelante"
RECOGNITION_MODE_BACKWARD = "atras"

MODE_LABELS = {
    RECOGNITION_MODE_FORWARD: "Encadenamiento hacia adelante",
    RECOGNITION_MODE_BACKWARD: "Encadenamiento hacia atrás",
}

MODE_DESCRIPTIONS = {
    RECOGNITION_MODE_FORWARD: (
        "Primero se agregan los hechos observables al sistema y luego las "
        "reglas disparan conclusiones sobre la especie."
    ),
    RECOGNITION_MODE_BACKWARD: (
        "Se plantea una hipótesis de especie y el sistema intenta demostrarla "
        "combinando subobjetivos de características."
    ),
}

# Feature configuration for bird taxonomy
FEATURE_GROUPS = {
    "ecological": ("habitat", "diet"),
    "morphological": ("morphology", "size"),
    "behavioral": ("activity",),
}

FEATURE_ORDER = tuple(
    feature
    for group in FEATURE_GROUPS.values()
    for feature in group
)

FEATURE_TRANSLATIONS = {
    "habitat": {
        "selva": "rainforest",
        "montana": "mountains",
        "bosque": "forest",
        "ciudad": "urban",
        "rio": "river",
        "costa_marina": "coastal",
        "humedal": "wetland",
        "sabana": "savanna",
    },
    "diet": {
        "carnivoro": "carnivore",
        "insectivoro": "insectivore",
        "herbivoro": "herbivore",
        "omnivoro": "omnivore",
        "piscivoro": "piscivore",
        "nectarivoro": "nectarivore",
    },
    "morphology": {
        "pico_ganchudo": "hooked_beak",
        "pico_recto": "straight_beak",
        "pico_curvo": "curved_beak",
        "pico_corto": "short_beak",
        "pico_alargado": "elongated_beak",
        "garras_fuertes": "strong_talons",
        "ojos_grandes": "large_eyes",
        "alas_largas": "long_wings",
        "alas_cortas": "short_wings",
        "plumaje_oscuro": "dark_plumage",
        "plumaje_claro": "light_plumage",
        "plumaje_moteado": "spotted_plumage",
        "patas_palmeadas": "webbed_feet",
        "cuello_largo": "long_neck",
    },
    "size": {
        "muy_pequeno": "very_small",
        "pequeno": "small",
        "mediano": "medium",
        "grande": "large",
        "muy_grande": "very_large",
    },
    "activity": {
        "diurno": "diurnal",
        "nocturno": "nocturnal",
        "migratorio": "migratory",
        "residente": "resident",
    },
}

REVERSE_FEATURE_TRANSLATIONS = {
    feature: {english: spanish for spanish, english in mapping.items()}
    for feature, mapping in FEATURE_TRANSLATIONS.items()
}

FEATURE_LABELS = {
    "habitat": "Hábitat",
    "diet": "Tipo de alimentación",
    "morphology": "Morfología",
    "size": "Tamaño",
    "activity": "Actividad",
}

FEATURE_OPTIONS = {
    "habitat": [
        "selva",
        "montana",
        "bosque",
        "ciudad",
        "rio",
        "costa_marina",
        "humedal",
        "sabana",
    ],
    "diet": [
        "carnivoro",
        "insectivoro",
        "herbivoro",
        "omnivoro",
        "piscivoro",
        "nectarivoro",
    ],
    "morphology": [
        "pico_ganchudo",
        "pico_recto",
        "pico_curvo",
        "pico_corto",
        "pico_alargado",
        "garras_fuertes",
        "ojos_grandes",
        "alas_largas",
        "alas_cortas",
        "plumaje_oscuro",
        "plumaje_claro",
        "plumaje_moteado",
        "patas_palmeadas",
        "cuello_largo",
    ],
    "size": [
        "muy_pequeno",
        "pequeno",
        "mediano",
        "grande",
        "muy_grande",
    ],
    "activity": [
        "diurno",
        "nocturno",
        "migratorio",
        "residente",
    ],
}


def humanize_label(token: str) -> str:
    """Convert identifiers like 'pico_ganchudo' into readable labels."""
    return token.replace("_", " ").title()


FEATURE_DISPLAY_OPTIONS = {
    feature: [humanize_label(option) for option in options]
    for feature, options in FEATURE_OPTIONS.items()
}

FEATURE_DISPLAY_TO_VALUE = {
    feature: {humanize_label(option): option for option in options}
    for feature, options in FEATURE_OPTIONS.items()
}

EXAMPLE_PRESETS = {
    "Águila Real": {
        "habitat": "montana",
        "diet": "carnivoro",
        "morphology": "pico_ganchudo",
        "size": "muy_grande",
        "activity": "diurno",
    },
    "Búho Real": {
        "habitat": "bosque",
        "diet": "carnivoro",
        "morphology": "ojos_grandes",
        "size": "grande",
        "activity": "nocturno",
    },
    "Garza Azul": {
        "habitat": "humedal",
        "diet": "piscivoro",
        "morphology": "cuello_largo",
        "size": "grande",
        "activity": "diurno",
    },
    "Martín Pescador": {
        "habitat": "rio",
        "diet": "piscivoro",
        "morphology": "pico_alargado",
        "size": "pequeno",
        "activity": "residente",
    },
    "Tucán Pico Iris": {
        "habitat": "selva",
        "diet": "omnivoro",
        "morphology": "pico_alargado",
        "size": "mediano",
        "activity": "residente",
    },
    "Águila Arpía": {
        "habitat": "selva",
        "diet": "carnivoro",
        "morphology": "garras_fuertes",
        "size": "muy_grande",
        "activity": "residente",
    },
}


@dataclass(frozen=True)
class BirdSpecies:
    """Represents a bird species with taxonomic classification."""

    common_name_es: str
    scientific_name: str
    species_code: str
    class_name: str
    order: str
    family: str
    genus: str
    wingspan_cm: str        # e.g. "180–220 cm"
    weight_g: str           # e.g. "3000–6500 g"
    lifespan_years: str     # e.g. "hasta 30 años"
    conservation_status: str  # IUCN: LC, NT, VU, EN, CR
    fun_fact: str

@dataclass(frozen=True)
class BirdProfile:
    """Complete bird profile including taxonomy and features."""

    bird_id: str
    species: BirdSpecies
    features: dict[str, str]


@dataclass(frozen=True)
class BirdMatch:
    """Scored match returned by the inference engine."""

    bird_id: str
    common_name_es: str
    order: str
    family: str
    matched_features: int
    total_features: int
    score_percent: int
    is_exact: bool


@dataclass(frozen=True)
class TaxonomyMatch:
    """Result from inference engine."""

    bird_id: str
    common_name_es: str
    order: str
    family: str


# Verified bird species database
BIRD_SPECIES_DATABASE = {
    "aguila_real": BirdSpecies(
        common_name_es="Águila Real",
        scientific_name="Aquila chrysaetos",
        species_code="GOEA",
        class_name="Aves",
        order="Accipitriformes",
        family="Accipitridae",
        genus="Aquila",
        wingspan_cm="180–220 cm",
        weight_g="3000–6500 g",
        lifespan_years="hasta 32 años",
        conservation_status="LC",
        fun_fact="Puede alcanzar velocidades de 240 km/h en picada.",
    ),
    "gavilan_cola_roja": BirdSpecies(
        common_name_es="Gavilán Cola Roja",
        scientific_name="Buteo jamaicensis",
        species_code="RTHA",
        class_name="Aves",
        order="Accipitriformes",
        family="Accipitridae",
        genus="Buteo",
        wingspan_cm="105–141 cm",
        weight_g="690–1460 g",
        lifespan_years="hasta 25 años",
        conservation_status="LC",
        fun_fact="Su grito es el sonido de 'águila' más usado en películas y televisión.",
    ),
    "buho_real": BirdSpecies(
        common_name_es="Búho Real",
        scientific_name="Bubo virginianus",
        species_code="GHOW",
        class_name="Aves",
        order="Strigiformes",
        family="Strigidae",
        genus="Bubo",
        wingspan_cm="91–153 cm",
        weight_g="910–2500 g",
        lifespan_years="hasta 28 años",
        conservation_status="LC",
        fun_fact="Puede girar la cabeza 270°. Es uno de los pocos predadores del zorrillo.",
    ),
    "lechuza_campanario": BirdSpecies(
        common_name_es="Lechuza de Campanario",
        scientific_name="Tyto alba",
        species_code="BARN",
        class_name="Aves",
        order="Strigiformes",
        family="Tytonidae",
        genus="Tyto",
        wingspan_cm="80–95 cm",
        weight_g="224–710 g",
        lifespan_years="hasta 20 años",
        conservation_status="LC",
        fun_fact="Su disco facial actúa como una antena parabólica para localizar presas en completa oscuridad.",
    ),
    "cuervo_comun": BirdSpecies(
        common_name_es="Cuervo Común",
        scientific_name="Corvus corax",
        species_code="CORA",
        class_name="Aves",
        order="Passeriformes",
        family="Corvidae",
        genus="Corvus",
        wingspan_cm="115–150 cm",
        weight_g="689–1625 g",
        lifespan_years="hasta 21 años",
        conservation_status="LC",
        fun_fact="Tiene capacidad de resolución de problemas equivalente a la de un chimpancé de 7 años.",
    ),
    "golondrina_azul_blanca": BirdSpecies(
        common_name_es="Golondrina Azul y Blanca",
        scientific_name="Hirundo rustica",
        species_code="BASW",
        class_name="Aves",
        order="Passeriformes",
        family="Hirundinidae",
        genus="Hirundo",
        wingspan_cm="32–34 cm",
        weight_g="17–20 g",
        lifespan_years="hasta 11 años",
        conservation_status="LC",
        fun_fact="Recorre más de 10,000 km en su migración anual entre continentes.",
    ),
    "loro_amazonico": BirdSpecies(
        common_name_es="Loro Amazónico",
        scientific_name="Amazona viridis",
        species_code="AMPA",
        class_name="Aves",
        order="Psittaciformes",
        family="Psittacidae",
        genus="Amazona",
        wingspan_cm="38–43 cm",
        weight_g="270–500 g",
        lifespan_years="hasta 60 años",
        conservation_status="LC",
        fun_fact="Puede imitar el habla humana con notable precisión fonética.",
    ),
    "paloma_comun": BirdSpecies(
        common_name_es="Paloma Común",
        scientific_name="Columba livia",
        species_code="ROPI",
        class_name="Aves",
        order="Columbiformes",
        family="Columbidae",
        genus="Columba",
        wingspan_cm="62–72 cm",
        weight_g="265–380 g",
        lifespan_years="hasta 15 años",
        conservation_status="LC",
        fun_fact="Fue el primer animal domesticado por el ser humano para enviar mensajes.",
    ),
    "gaviota_pico_anillado": BirdSpecies(
        common_name_es="Gaviota Pico Anillado",
        scientific_name="Larus delawarensis",
        species_code="RBGU",
        class_name="Aves",
        order="Charadriiformes",
        family="Laridae",
        genus="Larus",
        wingspan_cm="112–124 cm",
        weight_g="300–700 g",
        lifespan_years="hasta 23 años",
        conservation_status="LC",
        fun_fact="Puede beber agua salada gracias a glándulas especiales que excretan la sal.",
    ),
    "cormoran_grande": BirdSpecies(
        common_name_es="Cormorán Grande",
        scientific_name="Phalacrocorax carbo",
        species_code="GRCO",
        class_name="Aves",
        order="Pelecaniformes",
        family="Phalacrocoracidae",
        genus="Phalacrocorax",
        wingspan_cm="121–149 cm",
        weight_g="1500–4000 g",
        lifespan_years="hasta 25 años",
        conservation_status="LC",
        fun_fact="A diferencia de la mayoría de las aves acuáticas, sus plumas no son impermeables y debe secarlas extendiendo las alas.",
    ),
    "garza_azul": BirdSpecies(
        common_name_es="Garza Azul",
        scientific_name="Ardea herodias",
        species_code="GBHE",
        class_name="Aves",
        order="Pelecaniformes",
        family="Ardeidae",
        genus="Ardea",
        wingspan_cm="167–201 cm",
        weight_g="1820–3630 g",
        lifespan_years="hasta 24 años",
        conservation_status="LC",
        fun_fact="Puede permanecer inmóvil durante horas esperando que un pez se acerque.",
    ),
    "grulla_canadiense": BirdSpecies(
        common_name_es="Grulla Canadiense",
        scientific_name="Antigone canadensis",
        species_code="SACR",
        class_name="Aves",
        order="Gruiformes",
        family="Gruidae",
        genus="Antigone",
        wingspan_cm="155–200 cm",
        weight_g="3400–4500 g",
        lifespan_years="hasta 36 años",
        conservation_status="LC",
        fun_fact="Sus llamadas pueden escucharse a más de 3 km de distancia.",
    ),
    "halcon_peregrino": BirdSpecies(
        common_name_es="Halcón Peregrino",
        scientific_name="Falco peregrinus",
        species_code="PERE",
        class_name="Aves",
        order="Falconiformes",
        family="Falconidae",
        genus="Falco",
        wingspan_cm="89–120 cm",
        weight_g="330–1500 g",
        lifespan_years="hasta 19 años",
        conservation_status="LC",
        fun_fact="Es el animal más rápido del planeta, alcanzando 389 km/h en picada.",
    ),
    "pajaro_carpintero": BirdSpecies(
        common_name_es="Pájaro Carpintero",
        scientific_name="Dryocopus lineatus",
        species_code="WOOD",
        class_name="Aves",
        order="Piciformes",
        family="Picidae",
        genus="Dryocopus",
        wingspan_cm="51–58 cm",
        weight_g="196–314 g",
        lifespan_years="hasta 12 años",
        conservation_status="LC",
        fun_fact="Puede golpear el árbol hasta 20 veces por segundo sin sufrir daño cerebral.",
    ),
    "colibri_amazonia": BirdSpecies(
        common_name_es="Colibrí Amazónico",
        scientific_name="Amazilia tzacatl",
        species_code="HUMM",
        class_name="Aves",
        order="Apodiformes",
        family="Trochilidae",
        genus="Amazilia",
        wingspan_cm="10–12 cm",
        weight_g="4–6 g",
        lifespan_years="hasta 12 años",
        conservation_status="LC",
        fun_fact="Sus alas baten entre 50 y 80 veces por segundo, lo que produce su zumbido característico.",
    ),

    "martin_pescador": BirdSpecies(
        common_name_es="Martín Pescador",
        scientific_name="Megaceryle torquata",
        species_code="RIKI",
        class_name="Aves",
        order="Coraciiformes",
        family="Cerylidae",
        genus="Megaceryle",
        wingspan_cm="55–60 cm",
        weight_g="140–170 g",
        lifespan_years="hasta 7 años",
        conservation_status="LC",
        fun_fact="Puede sumergirse en el agua desde hasta 10 metros de altura con los ojos cerrados.",
    ),
    "pato_real": BirdSpecies(
        common_name_es="Pato Real",
        scientific_name="Anas platyrhynchos",
        species_code="MALL",
        class_name="Aves",
        order="Anseriformes",
        family="Anatidae",
        genus="Anas",
        wingspan_cm="81–98 cm",
        weight_g="720–1600 g",
        lifespan_years="hasta 20 años",
        conservation_status="LC",
        fun_fact="El pato real es el ancestro de casi todas las razas de patos domésticos del mundo.",
    ),
    "aguila_pescadora": BirdSpecies(
        common_name_es="Águila Pescadora",
        scientific_name="Pandion haliaetus",
        species_code="OSPR",
        class_name="Aves",
        order="Accipitriformes",
        family="Pandionidae",
        genus="Pandion",
        wingspan_cm="152–167 cm",
        weight_g="1200–2000 g",
        lifespan_years="hasta 25 años",
        conservation_status="LC",
        fun_fact="Sus dedos tienen espinas microscópicas para sujetar peces resbaladizos.",
    ),
    "flamingo_americano": BirdSpecies(
        common_name_es="Flamenco Americano",
        scientific_name="Phoenicopterus ruber",
        species_code="AMFL",
        class_name="Aves",
        order="Phoenicopteriformes",
        family="Phoenicopteridae",
        genus="Phoenicopterus",
        wingspan_cm="95–100 cm",
        weight_g="2200–2800 g",
        lifespan_years="hasta 40 años",
        conservation_status="LC",
        fun_fact="Su color rosado proviene de los pigmentos carotenoides de los crustáceos que consume.",
    ),
    "buitre_negro": BirdSpecies(
        common_name_es="Buitre Negro",
        scientific_name="Coragyps atratus",
        species_code="BLVU",
        class_name="Aves",
        order="Cathartiformes",
        family="Cathartidae",
        genus="Coragyps",
        wingspan_cm="133–160 cm",
        weight_g="1640–2260 g",
        lifespan_years="hasta 25 años",
        conservation_status="LC",
        fun_fact="Su estómago tiene un pH de casi 0, capaz de destruir el ántrax y el cólera sin afectarle.",
    ),
    "tucán_pico_iris": BirdSpecies(
        common_name_es="Tucán Pico Iris",
        scientific_name="Ramphastos sulfuratus",
        species_code="KBTO",
        class_name="Aves",
        order="Piciformes",
        family="Ramphastidae",
        genus="Ramphastos",
        wingspan_cm="43–50 cm",
        weight_g="130–200 g",
        lifespan_years="hasta 20 años",
        conservation_status="LC",
        fun_fact="Su enorme pico es hueco y ligero; actúa como regulador de temperatura corporal.",
    ),
    "aguila_arpía": BirdSpecies(
        common_name_es="Águila Arpía",
        scientific_name="Harpia harpyja",
        species_code="HARP",
        class_name="Aves",
        order="Accipitriformes",
        family="Accipitridae",
        genus="Harpia",
        wingspan_cm="176–224 cm",
        weight_g="4000–9000 g",
        lifespan_years="hasta 35 años",
        conservation_status="VU",
        fun_fact="Tiene las garras más grandes de cualquier águila viva, capaces de ejercer 530 N de presión.",
    ),
    "cigüeña_blanca": BirdSpecies(
        common_name_es="Cigüeña Blanca",
        scientific_name="Ciconia ciconia",
        species_code="WHST",
        class_name="Aves",
        order="Ciconiiformes",
        family="Ciconiidae",
        genus="Ciconia",
        wingspan_cm="195–215 cm",
        weight_g="2300–4400 g",
        lifespan_years="hasta 39 años",
        conservation_status="LC",
        fun_fact="Puede recorrer más de 20,000 km en su migración entre Europa y el sur de África.",
    ),
    "cotorra_monje": BirdSpecies(
        common_name_es="Cotorra Monje",
        scientific_name="Myiopsitta monachus",
        species_code="MONK",
        class_name="Aves",
        order="Psittaciformes",
        family="Psittacidae",
        genus="Myiopsitta",
        wingspan_cm="42–48 cm",
        weight_g="90–140 g",
        lifespan_years="hasta 30 años",
        conservation_status="LC",
        fun_fact="Es el único loro que construye nidos comunales con ramas, en lugar de anidar en cavidades.",
    ),
    "aguila_culebrera": BirdSpecies(
        common_name_es="Águila Culebrera",
        scientific_name="Circaetus gallicus",
        species_code="SHOR",
        class_name="Aves",
        order="Accipitriformes",
        family="Accipitridae",
        genus="Circaetus",
        wingspan_cm="162–195 cm",
        weight_g="1200–2300 g",
        lifespan_years="hasta 17 años",
        conservation_status="LC",
        fun_fact="Puede planearse en el aire durante minutos mirando al suelo en busca de serpientes.",
    ),
    "mochuelo_europeo": BirdSpecies(
        common_name_es="Mochuelo Europeo",
        scientific_name="Athene noctua",
        species_code="LTOW",
        class_name="Aves",
        order="Strigiformes",
        family="Strigidae",
        genus="Athene",
        wingspan_cm="54–58 cm",
        weight_g="140–220 g",
        lifespan_years="hasta 16 años",
        conservation_status="LC",
        fun_fact="A diferencia de la mayoría de los búhos, también caza de día. Era el símbolo de Atenea en la antigua Grecia.",
    ),
    "aguila_cola_blanca": BirdSpecies(
        common_name_es="Águila Cola Blanca",
        scientific_name="Haliaeetus albicilla",
        species_code="WTEA",
        class_name="Aves",
        order="Accipitriformes",
        family="Accipitridae",
        genus="Haliaeetus",
        wingspan_cm="193–244 cm",
        weight_g="3100–6900 g",
        lifespan_years="hasta 27 años",
        conservation_status="LC",
        fun_fact="Es el águila con mayor envergadura de Europa y pariente cercana del águila calva americana.",
    ),
    "somormujo_lavanco": BirdSpecies(
        common_name_es="Somormujo Lavanco",
        scientific_name="Podiceps cristatus",
        species_code="GCGR",
        class_name="Aves",
        order="Podicipediformes",
        family="Podicipedidae",
        genus="Podiceps",
        wingspan_cm="59–73 cm",
        weight_g="750–1490 g",
        lifespan_years="hasta 19 años",
        conservation_status="LC",
        fun_fact="Sus polluelos nacen con rayas y viajan sobre la espalda de los padres durante las primeras semanas.",
    ),
    "ibis_sagrado": BirdSpecies(
        common_name_es="Ibis Sagrado",
        scientific_name="Threskiornis aethiopicus",
        species_code="AFSI",
        class_name="Aves",
        order="Pelecaniformes",
        family="Threskiornithidae",
        genus="Threskiornis",
        wingspan_cm="112–124 cm",
        weight_g="1350–1500 g",
        lifespan_years="hasta 27 años",
        conservation_status="LC",
        fun_fact="Era considerado sagrado en el Antiguo Egipto y asociado al dios Thoth, dios de la sabiduría.",
    ),
    "espatula_rosada": BirdSpecies(
        common_name_es="Espátula Rosada",
        scientific_name="Platalea ajaja",
        species_code="ROSP",
        class_name="Aves",
        order="Pelecaniformes",
        family="Threskiornithidae",
        genus="Platalea",
        wingspan_cm="120–133 cm",
        weight_g="1200–1800 g",
        lifespan_years="hasta 16 años",
        conservation_status="LC",
        fun_fact="Su pico en forma de espátula lo mueve de lado a lado en el agua para filtrar crustáceos táctilmente.",
    ),
    "alcatraz_atlantico": BirdSpecies(
        common_name_es="Alcatraz Atlántico",
        scientific_name="Morus bassanus",
        species_code="NOGA",
        class_name="Aves",
        order="Suliformes",
        family="Sulidae",
        genus="Morus",
        wingspan_cm="165–180 cm",
        weight_g="2200–3600 g",
        lifespan_years="hasta 37 años",
        conservation_status="LC",
        fun_fact="Se lanza en picada desde 30 metros de altura alcanzando 100 km/h para capturar peces bajo el agua.",
    ),
    "avestruz": BirdSpecies(
        common_name_es="Avestruz",
        scientific_name="Struthio camelus",
        species_code="OSTR",
        class_name="Aves",
        order="Struthioniformes",
        family="Struthionidae",
        genus="Struthio",
        wingspan_cm="N/A (alas vestigiales)",
        weight_g="63000–145000 g",
        lifespan_years="hasta 45 años",
        conservation_status="LC",
        fun_fact="Es el ave más grande del mundo y puede correr a 70 km/h, la velocidad terrestre más alta de cualquier ave.",
    ),
    "aguila_marcial": BirdSpecies(
        common_name_es="Águila Marcial",
        scientific_name="Polemaetus bellicosus",
        species_code="MARE",
        class_name="Aves",
        order="Accipitriformes",
        family="Accipitridae",
        genus="Polemaetus",
        wingspan_cm="188–227 cm",
        weight_g="3000–6200 g",
        lifespan_years="hasta 25 años",
        conservation_status="VU",
        fun_fact="Es el águila más grande de África y puede ver un ser humano a más de 6 km de distancia.",
    ),
    "marabu_africano": BirdSpecies(
        common_name_es="Marabú Africano",
        scientific_name="Leptoptilos crumenifer",
        species_code="AFMA",
        class_name="Aves",
        order="Ciconiiformes",
        family="Ciconiidae",
        genus="Leptoptilos",
        wingspan_cm="225–287 cm",
        weight_g="4000–8900 g",
        lifespan_years="hasta 41 años",
        conservation_status="LC",
        fun_fact="Tiene la mayor envergadura de cualquier ave terrestre. Su bolsa gular rosada puede inflarse como globo.",
    ),
    "charao": BirdSpecies(
        common_name_es="Charão",
        scientific_name="Amazona pretrei",
        species_code="REAR",
        class_name="Aves",
        order="Psittaciformes",
        family="Psittacidae",
        genus="Amazona",
        wingspan_cm="35–40 cm",
        weight_g="250–330 g",
        lifespan_years="hasta 50 años",
        conservation_status="EN",
        fun_fact="Es uno de los loros más amenazados de Sudamérica, con menos de 10,000 individuos silvestres.",
    ),
    "herreruelo_comun": BirdSpecies(
        common_name_es="Herrerillo Común",
        scientific_name="Cyanistes caeruleus",
        species_code="EUBI",
        class_name="Aves",
        order="Passeriformes",
        family="Paridae",
        genus="Cyanistes",
        wingspan_cm="17–20 cm",
        weight_g="9–12 g",
        lifespan_years="hasta 10 años",
        conservation_status="LC",
        fun_fact="Aprende a abrir tapas de botellas de leche para acceder a la nata. Uno de los pocos casos documentados de aprendizaje cultural en aves.",
    ),
    "reyezuelo_sencillo": BirdSpecies(
        common_name_es="Reyezuelo Sencillo",
        scientific_name="Regulus regulus",
        species_code="GOLD",
        class_name="Aves",
        order="Passeriformes",
        family="Regulidae",
        genus="Regulus",
        wingspan_cm="13–16 cm",
        weight_g="4–7 g",
        lifespan_years="hasta 5 años",
        conservation_status="LC",
        fun_fact="Es el ave más pequeña de Europa. Pesa lo mismo que una moneda de 5 céntimos.",
    ),
    "avetoro_comun": BirdSpecies(
        common_name_es="Avetoro Común",
        scientific_name="Botaurus stellaris",
        species_code="EUBI2",
        class_name="Aves",
        order="Pelecaniformes",
        family="Ardeidae",
        genus="Botaurus",
        wingspan_cm="100–130 cm",
        weight_g="870–1940 g",
        lifespan_years="hasta 11 años",
        conservation_status="LC",
        fun_fact="Su llamada grave resuena hasta 5 km de distancia. Cuando se siente amenazado, estira el cuello y apunta el pico al cielo mimetizándose con los juncos.",
    ),
    "sisonte": BirdSpecies(
        common_name_es="Sisonte",
        scientific_name="Mimus polyglottos",
        species_code="NOMO",
        class_name="Aves",
        order="Passeriformes",
        family="Mimidae",
        genus="Mimus",
        wingspan_cm="31–38 cm",
        weight_g="45–58 g",
        lifespan_years="hasta 14 años",
        conservation_status="LC",
        fun_fact="Puede imitar los cantos de hasta 200 especies distintas de aves, así como sonidos mecánicos y llamadas de ranas.",
    ),
    "aguila_volatinera": BirdSpecies(
        common_name_es="Águila Volatinera",
        scientific_name="Terathopius ecaudatus",
        species_code="BATE",
        class_name="Aves",
        order="Accipitriformes",
        family="Accipitridae",
        genus="Terathopius",
        wingspan_cm="168–185 cm",
        weight_g="1900–2700 g",
        lifespan_years="hasta 27 años",
        conservation_status="VU",
        fun_fact="Puede planear hasta 8 horas sin batir las alas, cubriendo más de 700 km diarios sobre la sabana africana.",
    ),
}
# Profiles with verified taxonomic characteristics
BIRD_PROFILES = [
    BirdProfile(
        bird_id="aguila_real",
        species=BIRD_SPECIES_DATABASE["aguila_real"],
        features={
            "habitat": "mountains",
            "diet": "carnivore",
            "morphology": "hooked_beak",
            "size": "very_large",
            "activity": "diurnal",
            "behavior": "hunter",
        },
    ),
    BirdProfile(
        bird_id="gavilan_cola_roja",
        species=BIRD_SPECIES_DATABASE["gavilan_cola_roja"],
        features={
            "habitat": "forest",
            "diet": "carnivore",
            "morphology": "hooked_beak",
            "size": "large",
            "activity": "diurnal",
            "behavior": "hunter",
        },
    ),
    BirdProfile(
        bird_id="buho_real",
        species=BIRD_SPECIES_DATABASE["buho_real"],
        features={
            "habitat": "forest",
            "diet": "carnivore",
            "morphology": "large_eyes",
            "size": "large",
            "activity": "nocturnal",
            "behavior": "hunter",
        },
    ),
    BirdProfile(
        bird_id="lechuza_campanario",
        species=BIRD_SPECIES_DATABASE["lechuza_campanario"],
        features={
            "habitat": "urban",
            "diet": "carnivore",
            "morphology": "short_beak",
            "size": "medium",
            "activity": "nocturnal",
            "behavior": "hunter",
        },
    ),
    BirdProfile(
        bird_id="cuervo_comun",
        species=BIRD_SPECIES_DATABASE["cuervo_comun"],
        features={
            "habitat": "urban",
            "diet": "omnivore",
            "morphology": "dark_plumage",
            "size": "large",
            "activity": "diurnal",
            "behavior": "forager",
        },
    ),
    BirdProfile(
        bird_id="golondrina_azul_blanca",
        species=BIRD_SPECIES_DATABASE["golondrina_azul_blanca"],
        features={
            "habitat": "urban",
            "diet": "insectivore",
            "morphology": "long_wings",
            "size": "small",
            "activity": "migratory",
            "behavior": "forager",
        },
    ),
    BirdProfile(
        bird_id="loro_amazonico",
        species=BIRD_SPECIES_DATABASE["loro_amazonico"],
        features={
            "habitat": "rainforest",
            "diet": "herbivore",
            "morphology": "curved_beak",
            "size": "large",
            "activity": "diurnal",
            "behavior": "forager",
        },
    ),
    BirdProfile(
        bird_id="paloma_comun",
        species=BIRD_SPECIES_DATABASE["paloma_comun"],
        features={
            "habitat": "urban",
            "diet": "herbivore",
            "morphology": "straight_beak",
            "size": "medium",
            "activity": "diurnal",
            "behavior": "forager",
        },
    ),
    BirdProfile(
        bird_id="gaviota_pico_anillado",
        species=BIRD_SPECIES_DATABASE["gaviota_pico_anillado"],
        features={
            "habitat": "coastal",
            "diet": "omnivore",
            "morphology": "webbed_feet",
            "size": "medium",
            "activity": "diurnal",
            "behavior": "forager",
        },
    ),
    BirdProfile(
        bird_id="cormoran_grande",
        species=BIRD_SPECIES_DATABASE["cormoran_grande"],
        features={
            "habitat": "coastal",
            "diet": "piscivore",
            "morphology": "elongated_beak",
            "size": "large",
            "activity": "diurnal",
            "behavior": "fisher",
        },
    ),
    BirdProfile(
        bird_id="garza_azul",
        species=BIRD_SPECIES_DATABASE["garza_azul"],
        features={
            "habitat": "wetland",
            "diet": "piscivore",
            "morphology": "long_neck",
            "size": "large",
            "activity": "diurnal",
            "behavior": "fisher",
        },
    ),
    BirdProfile(
        bird_id="grulla_canadiense",
        species=BIRD_SPECIES_DATABASE["grulla_canadiense"],
        features={
            "habitat": "wetland",
            "diet": "omnivore",
            "morphology": "long_neck",
            "size": "very_large",
            "activity": "migratory",
            "behavior": "forager",
        },
    ),
    BirdProfile(
        bird_id="halcon_peregrino",
        species=BIRD_SPECIES_DATABASE["halcon_peregrino"],
        features={
            "habitat": "coastal",
            "diet": "carnivore",
            "morphology": "hooked_beak",
            "size": "medium",
            "activity": "diurnal",
            "behavior": "hunter",
        },
    ),
    BirdProfile(
        bird_id="pajaro_carpintero",
        species=BIRD_SPECIES_DATABASE["pajaro_carpintero"],
        features={
            "habitat": "forest",
            "diet": "insectivore",
            "morphology": "straight_beak",
            "size": "medium",
            "activity": "diurnal",
            "behavior": "forager",
        },
    ),
    BirdProfile(
        bird_id="colibri_amazonia",
        species=BIRD_SPECIES_DATABASE["colibri_amazonia"],
        features={
            "habitat": "rainforest",
            "diet": "nectarivore",
            "morphology": "long_wings",
            "size": "very_small",
            "activity": "diurnal",
            "behavior": "forager",
        },
    ),
    BirdProfile(
        bird_id="martin_pescador",
        species=BIRD_SPECIES_DATABASE["martin_pescador"],
        features={
            "habitat": "river",
            "diet": "piscivore",
            "morphology": "elongated_beak",
            "size": "small",
            "activity": "resident",
            "behavior": "fisher",
        },
    ),
    BirdProfile(
        bird_id="pato_real",
        species=BIRD_SPECIES_DATABASE["pato_real"],
        features={
            "habitat": "river",
            "diet": "omnivore",
            "morphology": "webbed_feet",
            "size": "medium",
            "activity": "resident",
            "behavior": "forager",
        },
    ),
    BirdProfile(
        bird_id="aguila_pescadora",
        species=BIRD_SPECIES_DATABASE["aguila_pescadora"],
        features={
            "habitat": "coastal",
            "diet": "piscivore",
            "morphology": "strong_talons",
            "size": "large",
            "activity": "migratory",
            "behavior": "fisher",
        },
    ),
    BirdProfile(
        bird_id="flamingo_americano",
        species=BIRD_SPECIES_DATABASE["flamingo_americano"],
        features={
            "habitat": "wetland",
            "diet": "omnivore",
            "morphology": "long_neck",
            "size": "large",
            "activity": "resident",
            "behavior": "forager",
        },
    ),
    BirdProfile(
        bird_id="buitre_negro",
        species=BIRD_SPECIES_DATABASE["buitre_negro"],
        features={
            "habitat": "savanna",
            "diet": "carnivore",
            "morphology": "dark_plumage",
            "size": "large",
            "activity": "diurnal",
            "behavior": "glider",
        },
    ),
    BirdProfile(
        bird_id="tucan_pico_iris",
        species=BIRD_SPECIES_DATABASE["tucán_pico_iris"],
        features={
            "habitat": "rainforest",
            "diet": "omnivore",
            "morphology": "elongated_beak",
            "size": "medium",
            "activity": "resident",
            "behavior": "forager",
        },
    ),
    BirdProfile(
        bird_id="aguila_arpia",
        species=BIRD_SPECIES_DATABASE["aguila_arpía"],
        features={
            "habitat": "rainforest",
            "diet": "carnivore",
            "morphology": "strong_talons",
            "size": "very_large",
            "activity": "resident",
            "behavior": "hunter",
        },
    ),
    BirdProfile(
        bird_id="cigüeña_blanca",
        species=BIRD_SPECIES_DATABASE["cigüeña_blanca"],
        features={
            "habitat": "savanna",
            "diet": "omnivore",
            "morphology": "long_neck",
            "size": "very_large",
            "activity": "migratory",
            "behavior": "forager",
        },
    ),
    BirdProfile(
        bird_id="cotorra_monje",
        species=BIRD_SPECIES_DATABASE["cotorra_monje"],
        features={
            "habitat": "urban",
            "diet": "herbivore",
            "morphology": "curved_beak",
            "size": "small",
            "activity": "resident",
            "behavior": "forager",
        },
    ),
    BirdProfile(
        bird_id="aguila_culebrera",
        species=BIRD_SPECIES_DATABASE["aguila_culebrera"],
        features={
            "habitat": "savanna",
            "diet": "carnivore",
            "morphology": "hooked_beak",
            "size": "large",
            "activity": "diurnal",
            "behavior": "glider",
        },
    ),
    BirdProfile(
        bird_id="mochuelo_europeo",
        species=BIRD_SPECIES_DATABASE["mochuelo_europeo"],
        features={
            "habitat": "forest",
            "diet": "insectivore",
            "morphology": "large_eyes",
            "size": "small",
            "activity": "nocturnal",
            "behavior": "hunter",
        },
    ),
    BirdProfile(
        bird_id="aguila_cola_blanca",
        species=BIRD_SPECIES_DATABASE["aguila_cola_blanca"],
        features={
            "habitat": "river",
            "diet": "piscivore",
            "morphology": "hooked_beak",
            "size": "very_large",
            "activity": "resident",
            "behavior": "hunter",
        },
    ),
    BirdProfile(
        bird_id="somormujo_lavanco",
        species=BIRD_SPECIES_DATABASE["somormujo_lavanco"],
        features={
            "habitat": "river",
            "diet": "piscivore",
            "morphology": "straight_beak",
            "size": "medium",
            "activity": "resident",
            "behavior": "fisher",
        },
    ),
    BirdProfile(
        bird_id="ibis_sagrado",
        species=BIRD_SPECIES_DATABASE["ibis_sagrado"],
        features={
            "habitat": "wetland",
            "diet": "omnivore",
            "morphology": "curved_beak",
            "size": "medium",
            "activity": "resident",
            "behavior": "forager",
        },
    ),
    BirdProfile(
        bird_id="espatula_rosada",
        species=BIRD_SPECIES_DATABASE["espatula_rosada"],
        features={
            "habitat": "wetland",
            "diet": "omnivore",
            "morphology": "light_plumage",
            "size": "large",
            "activity": "resident",
            "behavior": "forager",
        },
    ),
    BirdProfile(
        bird_id="alcatraz_atlantico",
        species=BIRD_SPECIES_DATABASE["alcatraz_atlantico"],
        features={
            "habitat": "coastal",
            "diet": "piscivore",
            "morphology": "light_plumage",
            "size": "large",
            "activity": "migratory",
            "behavior": "fisher",
        },
    ),
    BirdProfile(
        bird_id="avestruz",
        species=BIRD_SPECIES_DATABASE["avestruz"],
        features={
            "habitat": "savanna",
            "diet": "herbivore",
            "morphology": "short_wings",
            "size": "very_large",
            "activity": "resident",
            "behavior": "forager",
        },
    ),
    BirdProfile(
        bird_id="aguila_marcial",
        species=BIRD_SPECIES_DATABASE["aguila_marcial"],
        features={
            "habitat": "savanna",
            "diet": "carnivore",
            "morphology": "spotted_plumage",
            "size": "very_large",
            "activity": "diurnal",
            "behavior": "hunter",
        },
    ),
    BirdProfile(
        bird_id="marabu_africano",
        species=BIRD_SPECIES_DATABASE["marabu_africano"],
        features={
            "habitat": "savanna",
            "diet": "carnivore",
            "morphology": "elongated_beak",
            "size": "very_large",
            "activity": "diurnal",
            "behavior": "glider",
        },
    ),
    BirdProfile(
        bird_id="charao",
        species=BIRD_SPECIES_DATABASE["charao"],
        features={
            "habitat": "forest",
            "diet": "herbivore",
            "morphology": "curved_beak",
            "size": "medium",
            "activity": "resident",
            "behavior": "forager",
        },
    ),
    BirdProfile(
        bird_id="herreruelo_comun",
        species=BIRD_SPECIES_DATABASE["herreruelo_comun"],
        features={
            "habitat": "forest",
            "diet": "insectivore",
            "morphology": "short_beak",
            "size": "very_small",
            "activity": "resident",
            "behavior": "forager",
        },
    ),
    BirdProfile(
        bird_id="reyezuelo_sencillo",
        species=BIRD_SPECIES_DATABASE["reyezuelo_sencillo"],
        features={
            "habitat": "forest",
            "diet": "insectivore",
            "morphology": "short_beak",
            "size": "very_small",
            "activity": "migratory",
            "behavior": "forager",
        },
    ),
    BirdProfile(
        bird_id="avetoro_comun",
        species=BIRD_SPECIES_DATABASE["avetoro_comun"],
        features={
            "habitat": "wetland",
            "diet": "piscivore",
            "morphology": "spotted_plumage",
            "size": "large",
            "activity": "nocturnal",
            "behavior": "hunter",
        },
    ),
    BirdProfile(
        bird_id="sisonte",
        species=BIRD_SPECIES_DATABASE["sisonte"],
        features={
            "habitat": "urban",
            "diet": "omnivore",
            "morphology": "straight_beak",
            "size": "small",
            "activity": "resident",
            "behavior": "forager",
        },
    ),
    BirdProfile(
        bird_id="aguila_volatinera",
        species=BIRD_SPECIES_DATABASE["aguila_volatinera"],
        features={
            "habitat": "savanna",
            "diet": "carnivore",
            "morphology": "short_wings",
            "size": "large",
            "activity": "diurnal",
            "behavior": "glider",
        },
    ),
]
